### ISSUE TITLE
Naima does not handle well the time-dependent particle spectra while fitting

### ISSUE THREAD

**Issue by wrijupan** [wrijupan/blazar_model#1]
https://github.com/cosimoNigro/blazar_model/issues/1

**Comment by vaidehiratna** [comment]
Hi Wrijupan,

I am not an expert in theoretical modeling but I work on blazars. I gave a try to your fitting script and also used the sample data file you have provided. After running, it opened a GUI and closing which throws the following error

Traceback (most recent call last):
  File "fitmodel.py", line 250, in <module>
    fitter_obj.main()
  File "fitmodel.py", line 244, in main
    self.fitter(p_init, labels, xray, vhe)
  File "fitmodel.py", line 215, in fitter
    interactive=False)
  File "/Library/Python/2.7/site-packages/naima/core.py", line 498, in run_sampler
    sampler, pos = get_sampler(**kwargs)
  File "/Library/Python/2.7/site-packages/naima/core.py", line 334, in get_sampler
    data = validate_data_table(data_table, sed=data_sed)
  File "/Library/Python/2.7/site-packages/naima/utils.py", line 80, in validate_data_table
    dt_val = _validate_single_data_table(dt, group=group)
  File "/Library/Python/2.7/site-packages/naima/utils.py", line 114, in _validate_single_data_table
    data['energy'] = validate_column(data_table, 'energy', 'energy')
  File "/Library/Python/2.7/site-packages/naima/utils.py", line 28, in validate_column
    domain=domain)
  File "/Library/Python/2.7/site-packages/naima/extern/validator.py", line 49, in validate_array
    validate_physical_type(name, value, physical_type)
  File "/Library/Python/2.7/site-packages/naima/extern/validator.py", line 14, in validate_physical_type
    raise TypeError("{0} should be given in units of {1}".format(name, physical_type))
TypeError: energy should be given in units of energy

Hope this may help in improving the code. If you could add the EC spectrum calculation, then it would be even better.

Thanks.

Vaidehi

**Comment by wrijupan** [comment]
@vaidehiratna Your problem seems to be that `energy` column from the data table in ECSV format could not be validated as `type=energy`. Maybe this is because your environment cannot read an ECSV file, where units are specified in the metadata. Reading an ECSV file correctly, requires the pyyaml package. Please check if you have it installed.
If not, try : `conda install pyyaml`
